#!/usr/bin/env bash
# One-time (idempotent) provisioning of everything this demo needs on the
# JFrog Platform side:
#   1. A generic-local repo for immutable, long-retention firmware releases.
#   2. A generic-local repo used as ccache's HTTP secondary storage, so any
#      build machine (incl. slow Windows dev boxes) shares one pre-built
#      object cache instead of recompiling from scratch.
#   3. An ECDSA signing key for certification evidence, plus a scoped
#      access token for ccache to authenticate with.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
source scripts/common.sh

echo "==> Target: ${SERVER_ID}"

repo_exists() {
  jf rt curl -s -o /dev/null -w "%{http_code}" "/api/repositories/$1" --server-id="${SERVER_ID}" | grep -q "^200$"
}

create_repo() {
  local key="$1" template="$2"
  if repo_exists "${key}"; then
    echo "==> Repo '${key}' already exists, skipping."
  else
    echo "==> Creating repo '${key}'..."
    jf rt repo-create "repo-templates/${template}" --server-id="${SERVER_ID}"
  fi
}

create_repo "${GENERIC_REPO}" "generic-local.json"
create_repo "${CCACHE_REPO}" "ccache-local.json"

echo "==> Generating evidence signing keypair (if not already present)..."
if [[ -f evidence-keys/envsensor-cert.key ]]; then
  echo "==> Signing key already present at evidence-keys/envsensor-cert.key, skipping."
else
  mkdir -p evidence-keys
  jf evd generate-key-pair \
    --key-file-name envsensor-cert \
    --key-file-path evidence-keys \
    --key-alias envsensor-cert-key \
    --server-id="${SERVER_ID}"
fi

echo "==> Minting a scoped access token for ccache HTTP secondary storage..."
ARTIFACTORY_URL="$(jf config show "${SERVER_ID}" | awk '/Artifactory URL:/ {print $3; exit}')"

TOKEN_JSON="$(jf access-token-create \
  --description "envsensor-fw ccache secondary storage (demo)" \
  --expiry 2592000 \
  --server-id="${SERVER_ID}")"
CCACHE_TOKEN="$(echo "${TOKEN_JSON}" | jq -r '.access_token')"
TOKEN_USER="$(echo "${TOKEN_JSON}" | jq -r '.username // empty')"

cat > .env <<EOF
# Generated by scripts/setup_artifactory.sh — DO NOT COMMIT (gitignored).
# Token expires in 30 days; re-run setup_artifactory.sh to mint a new one.
ARTIFACTORY_URL="${ARTIFACTORY_URL}"
ARTIFACTORY_CCACHE_TOKEN="${CCACHE_TOKEN}"
ARTIFACTORY_CCACHE_USER="${TOKEN_USER}"
EOF

echo "==> Wrote .env with a fresh 30-day access token."
echo "==> Setup complete:"
echo "      generic repo : ${GENERIC_REPO}"
echo "      ccache repo  : ${CCACHE_REPO}"
echo "      signing key  : evidence-keys/envsensor-cert.key (public key uploaded to trusted keys)"
